modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "devauth"
version = "${version}"
displayName = "DevAuth"
authors = "DJtheRedstoner"
description = "Safely authenticate Minecraft accounts in development environments."
logoFile = "assets/devauth/logo.png"
